// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyStruct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MyStruct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MyStruct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MyStruct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MyStruct_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MyStruct_2eproto;
namespace PROTOCOL {
class PLAYER;
struct PLAYERDefaultTypeInternal;
extern PLAYERDefaultTypeInternal _PLAYER_default_instance_;
class PLAYERLIST;
struct PLAYERLISTDefaultTypeInternal;
extern PLAYERLISTDefaultTypeInternal _PLAYERLIST_default_instance_;
}  // namespace PROTOCOL
PROTOBUF_NAMESPACE_OPEN
template<> ::PROTOCOL::PLAYER* Arena::CreateMaybeMessage<::PROTOCOL::PLAYER>(Arena*);
template<> ::PROTOCOL::PLAYERLIST* Arena::CreateMaybeMessage<::PROTOCOL::PLAYERLIST>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PROTOCOL {

// ===================================================================

class PLAYER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PROTOCOL.PLAYER) */ {
 public:
  inline PLAYER() : PLAYER(nullptr) {}
  ~PLAYER() override;
  explicit constexpr PLAYER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PLAYER(const PLAYER& from);
  PLAYER(PLAYER&& from) noexcept
    : PLAYER() {
    *this = ::std::move(from);
  }

  inline PLAYER& operator=(const PLAYER& from) {
    CopyFrom(from);
    return *this;
  }
  inline PLAYER& operator=(PLAYER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PLAYER& default_instance() {
    return *internal_default_instance();
  }
  static inline const PLAYER* internal_default_instance() {
    return reinterpret_cast<const PLAYER*>(
               &_PLAYER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PLAYER& a, PLAYER& b) {
    a.Swap(&b);
  }
  inline void Swap(PLAYER* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PLAYER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PLAYER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PLAYER>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PLAYER& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PLAYER& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLAYER* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PROTOCOL.PLAYER";
  }
  protected:
  explicit PLAYER(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIDFieldNumber = 12,
    kPlayerIdFieldNumber = 1,
    kLocationXFieldNumber = 2,
    kLocationYFieldNumber = 3,
    kLocationZFieldNumber = 4,
    kRotationYawFieldNumber = 5,
    kRotationPitchFieldNumber = 6,
    kRotationRollFieldNumber = 7,
    kVelocityXFieldNumber = 8,
    kVelocityYFieldNumber = 9,
    kVelocityZFieldNumber = 10,
    kHpFieldNumber = 11,
  };
  // string ID = 12;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // uint64 playerId = 1;
  void clear_playerid();
  uint64_t playerid() const;
  void set_playerid(uint64_t value);
  private:
  uint64_t _internal_playerid() const;
  void _internal_set_playerid(uint64_t value);
  public:

  // float locationX = 2;
  void clear_locationx();
  float locationx() const;
  void set_locationx(float value);
  private:
  float _internal_locationx() const;
  void _internal_set_locationx(float value);
  public:

  // float locationY = 3;
  void clear_locationy();
  float locationy() const;
  void set_locationy(float value);
  private:
  float _internal_locationy() const;
  void _internal_set_locationy(float value);
  public:

  // float locationZ = 4;
  void clear_locationz();
  float locationz() const;
  void set_locationz(float value);
  private:
  float _internal_locationz() const;
  void _internal_set_locationz(float value);
  public:

  // float rotationYaw = 5;
  void clear_rotationyaw();
  float rotationyaw() const;
  void set_rotationyaw(float value);
  private:
  float _internal_rotationyaw() const;
  void _internal_set_rotationyaw(float value);
  public:

  // float rotationPitch = 6;
  void clear_rotationpitch();
  float rotationpitch() const;
  void set_rotationpitch(float value);
  private:
  float _internal_rotationpitch() const;
  void _internal_set_rotationpitch(float value);
  public:

  // float rotationRoll = 7;
  void clear_rotationroll();
  float rotationroll() const;
  void set_rotationroll(float value);
  private:
  float _internal_rotationroll() const;
  void _internal_set_rotationroll(float value);
  public:

  // float velocityX = 8;
  void clear_velocityx();
  float velocityx() const;
  void set_velocityx(float value);
  private:
  float _internal_velocityx() const;
  void _internal_set_velocityx(float value);
  public:

  // float velocityY = 9;
  void clear_velocityy();
  float velocityy() const;
  void set_velocityy(float value);
  private:
  float _internal_velocityy() const;
  void _internal_set_velocityy(float value);
  public:

  // float velocityZ = 10;
  void clear_velocityz();
  float velocityz() const;
  void set_velocityz(float value);
  private:
  float _internal_velocityz() const;
  void _internal_set_velocityz(float value);
  public:

  // float hp = 11;
  void clear_hp();
  float hp() const;
  void set_hp(float value);
  private:
  float _internal_hp() const;
  void _internal_set_hp(float value);
  public:

  // @@protoc_insertion_point(class_scope:PROTOCOL.PLAYER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  uint64_t playerid_;
  float locationx_;
  float locationy_;
  float locationz_;
  float rotationyaw_;
  float rotationpitch_;
  float rotationroll_;
  float velocityx_;
  float velocityy_;
  float velocityz_;
  float hp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MyStruct_2eproto;
};
// -------------------------------------------------------------------

class PLAYERLIST final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PROTOCOL.PLAYERLIST) */ {
 public:
  inline PLAYERLIST() : PLAYERLIST(nullptr) {}
  ~PLAYERLIST() override;
  explicit constexpr PLAYERLIST(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PLAYERLIST(const PLAYERLIST& from);
  PLAYERLIST(PLAYERLIST&& from) noexcept
    : PLAYERLIST() {
    *this = ::std::move(from);
  }

  inline PLAYERLIST& operator=(const PLAYERLIST& from) {
    CopyFrom(from);
    return *this;
  }
  inline PLAYERLIST& operator=(PLAYERLIST&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PLAYERLIST& default_instance() {
    return *internal_default_instance();
  }
  static inline const PLAYERLIST* internal_default_instance() {
    return reinterpret_cast<const PLAYERLIST*>(
               &_PLAYERLIST_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PLAYERLIST& a, PLAYERLIST& b) {
    a.Swap(&b);
  }
  inline void Swap(PLAYERLIST* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PLAYERLIST* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PLAYERLIST* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PLAYERLIST>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PLAYERLIST& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PLAYERLIST& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PLAYERLIST* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PROTOCOL.PLAYERLIST";
  }
  protected:
  explicit PLAYERLIST(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 1,
  };
  // repeated .PROTOCOL.PLAYER players = 1;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::PROTOCOL::PLAYER* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOCOL::PLAYER >*
      mutable_players();
  private:
  const ::PROTOCOL::PLAYER& _internal_players(int index) const;
  ::PROTOCOL::PLAYER* _internal_add_players();
  public:
  const ::PROTOCOL::PLAYER& players(int index) const;
  ::PROTOCOL::PLAYER* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOCOL::PLAYER >&
      players() const;

  // @@protoc_insertion_point(class_scope:PROTOCOL.PLAYERLIST)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOCOL::PLAYER > players_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MyStruct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PLAYER

// uint64 playerId = 1;
inline void PLAYER::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline uint64_t PLAYER::_internal_playerid() const {
  return playerid_;
}
inline uint64_t PLAYER::playerid() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.playerId)
  return _internal_playerid();
}
inline void PLAYER::_internal_set_playerid(uint64_t value) {
  
  playerid_ = value;
}
inline void PLAYER::set_playerid(uint64_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.playerId)
}

// float locationX = 2;
inline void PLAYER::clear_locationx() {
  locationx_ = 0;
}
inline float PLAYER::_internal_locationx() const {
  return locationx_;
}
inline float PLAYER::locationx() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.locationX)
  return _internal_locationx();
}
inline void PLAYER::_internal_set_locationx(float value) {
  
  locationx_ = value;
}
inline void PLAYER::set_locationx(float value) {
  _internal_set_locationx(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.locationX)
}

// float locationY = 3;
inline void PLAYER::clear_locationy() {
  locationy_ = 0;
}
inline float PLAYER::_internal_locationy() const {
  return locationy_;
}
inline float PLAYER::locationy() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.locationY)
  return _internal_locationy();
}
inline void PLAYER::_internal_set_locationy(float value) {
  
  locationy_ = value;
}
inline void PLAYER::set_locationy(float value) {
  _internal_set_locationy(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.locationY)
}

// float locationZ = 4;
inline void PLAYER::clear_locationz() {
  locationz_ = 0;
}
inline float PLAYER::_internal_locationz() const {
  return locationz_;
}
inline float PLAYER::locationz() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.locationZ)
  return _internal_locationz();
}
inline void PLAYER::_internal_set_locationz(float value) {
  
  locationz_ = value;
}
inline void PLAYER::set_locationz(float value) {
  _internal_set_locationz(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.locationZ)
}

// float rotationYaw = 5;
inline void PLAYER::clear_rotationyaw() {
  rotationyaw_ = 0;
}
inline float PLAYER::_internal_rotationyaw() const {
  return rotationyaw_;
}
inline float PLAYER::rotationyaw() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.rotationYaw)
  return _internal_rotationyaw();
}
inline void PLAYER::_internal_set_rotationyaw(float value) {
  
  rotationyaw_ = value;
}
inline void PLAYER::set_rotationyaw(float value) {
  _internal_set_rotationyaw(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.rotationYaw)
}

// float rotationPitch = 6;
inline void PLAYER::clear_rotationpitch() {
  rotationpitch_ = 0;
}
inline float PLAYER::_internal_rotationpitch() const {
  return rotationpitch_;
}
inline float PLAYER::rotationpitch() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.rotationPitch)
  return _internal_rotationpitch();
}
inline void PLAYER::_internal_set_rotationpitch(float value) {
  
  rotationpitch_ = value;
}
inline void PLAYER::set_rotationpitch(float value) {
  _internal_set_rotationpitch(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.rotationPitch)
}

// float rotationRoll = 7;
inline void PLAYER::clear_rotationroll() {
  rotationroll_ = 0;
}
inline float PLAYER::_internal_rotationroll() const {
  return rotationroll_;
}
inline float PLAYER::rotationroll() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.rotationRoll)
  return _internal_rotationroll();
}
inline void PLAYER::_internal_set_rotationroll(float value) {
  
  rotationroll_ = value;
}
inline void PLAYER::set_rotationroll(float value) {
  _internal_set_rotationroll(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.rotationRoll)
}

// float velocityX = 8;
inline void PLAYER::clear_velocityx() {
  velocityx_ = 0;
}
inline float PLAYER::_internal_velocityx() const {
  return velocityx_;
}
inline float PLAYER::velocityx() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.velocityX)
  return _internal_velocityx();
}
inline void PLAYER::_internal_set_velocityx(float value) {
  
  velocityx_ = value;
}
inline void PLAYER::set_velocityx(float value) {
  _internal_set_velocityx(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.velocityX)
}

// float velocityY = 9;
inline void PLAYER::clear_velocityy() {
  velocityy_ = 0;
}
inline float PLAYER::_internal_velocityy() const {
  return velocityy_;
}
inline float PLAYER::velocityy() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.velocityY)
  return _internal_velocityy();
}
inline void PLAYER::_internal_set_velocityy(float value) {
  
  velocityy_ = value;
}
inline void PLAYER::set_velocityy(float value) {
  _internal_set_velocityy(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.velocityY)
}

// float velocityZ = 10;
inline void PLAYER::clear_velocityz() {
  velocityz_ = 0;
}
inline float PLAYER::_internal_velocityz() const {
  return velocityz_;
}
inline float PLAYER::velocityz() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.velocityZ)
  return _internal_velocityz();
}
inline void PLAYER::_internal_set_velocityz(float value) {
  
  velocityz_ = value;
}
inline void PLAYER::set_velocityz(float value) {
  _internal_set_velocityz(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.velocityZ)
}

// float hp = 11;
inline void PLAYER::clear_hp() {
  hp_ = 0;
}
inline float PLAYER::_internal_hp() const {
  return hp_;
}
inline float PLAYER::hp() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.hp)
  return _internal_hp();
}
inline void PLAYER::_internal_set_hp(float value) {
  
  hp_ = value;
}
inline void PLAYER::set_hp(float value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.hp)
}

// string ID = 12;
inline void PLAYER::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& PLAYER::id() const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYER.ID)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PLAYER::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PROTOCOL.PLAYER.ID)
}
inline std::string* PLAYER::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:PROTOCOL.PLAYER.ID)
  return _s;
}
inline const std::string& PLAYER::_internal_id() const {
  return id_.Get();
}
inline void PLAYER::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PLAYER::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PLAYER::release_id() {
  // @@protoc_insertion_point(field_release:PROTOCOL.PLAYER.ID)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PLAYER::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PROTOCOL.PLAYER.ID)
}

// -------------------------------------------------------------------

// PLAYERLIST

// repeated .PROTOCOL.PLAYER players = 1;
inline int PLAYERLIST::_internal_players_size() const {
  return players_.size();
}
inline int PLAYERLIST::players_size() const {
  return _internal_players_size();
}
inline void PLAYERLIST::clear_players() {
  players_.Clear();
}
inline ::PROTOCOL::PLAYER* PLAYERLIST::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:PROTOCOL.PLAYERLIST.players)
  return players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOCOL::PLAYER >*
PLAYERLIST::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:PROTOCOL.PLAYERLIST.players)
  return &players_;
}
inline const ::PROTOCOL::PLAYER& PLAYERLIST::_internal_players(int index) const {
  return players_.Get(index);
}
inline const ::PROTOCOL::PLAYER& PLAYERLIST::players(int index) const {
  // @@protoc_insertion_point(field_get:PROTOCOL.PLAYERLIST.players)
  return _internal_players(index);
}
inline ::PROTOCOL::PLAYER* PLAYERLIST::_internal_add_players() {
  return players_.Add();
}
inline ::PROTOCOL::PLAYER* PLAYERLIST::add_players() {
  ::PROTOCOL::PLAYER* _add = _internal_add_players();
  // @@protoc_insertion_point(field_add:PROTOCOL.PLAYERLIST.players)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOCOL::PLAYER >&
PLAYERLIST::players() const {
  // @@protoc_insertion_point(field_list:PROTOCOL.PLAYERLIST.players)
  return players_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PROTOCOL

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MyStruct_2eproto
